[package]
name = "ferrous-core"
version = "0.5.0"
authors = ["Anish Jewalikar <anishjewalikar@gmail.com>"]
edition = "2018"
description = "A simple Chip-8 interpreter backend for Ferrous Chip-8."
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/NightShade256/oxidized-ch8"

[dependencies]
rand = "0.8"
