name: Rust

on: [release, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
        
      - name: Build
        run: cd ch8-sdl2
        run: cargo build --release --features "bundled"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/ch8-sdl2.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
